name: thoga_kade
description: A command-line vegetable shop management application
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^4.1.0
  intl: ^0.18.1

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0